# Generated by Django 4.0 on 2021-12-18 09:51

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя', max_length=200)),
                ('surname', models.CharField(help_text='Фамилия', max_length=200)),
                ('patronymic', models.CharField(help_text='Отчество', max_length=200)),
                ('position', models.CharField(max_length=150)),
                ('employment_date', models.DateTimeField()),
                ('salary', models.IntegerField(default=100000)),
                ('photo', models.ImageField(blank=True, default='1.jpg', upload_to='empl_photo')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('more_weighty', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='less_weighty', to='employee.employees_info')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
