# Generated by Django 4.0 on 2021-12-18 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees_info',
            old_name='more_weighty',
            new_name='parent',
        ),
    ]
